#  ----------------------------------------------------
#   Dummys Configuration File
#  ----------------------------------------------------

# Time to restart total damage after last hit (seconds)
DummyRestartTime: 4

# Set /dummy help message
HelpMessage:
    - "&c=======================================\n"
    - "&e/dummy create - Use to create a dummy\n"
    - "&e/dummy delete - Use to delete a dummy\n"
    - "&c=======================================\n"

# Set message when dummy can't be placed
NotHere: "&cYou cannot place that here!"

# Set message when entity is not dummy
NotDummy: "&cThis is not a dummy!"
