name: Dummys
version: 1.1
api-version: 1.16
author: Poxiton
main: com.github.poxiton.Dummys
commands:
   dummy:
      description: This is a dummy command.
      usage: /<command> [create | delete | help]
      permission: dummys.dummy
      permission-message: "§cYou don't have permission to use this command!"